# Template for Dockerizing applications

parameters:
  environment: ''  # The target environment (dev, integration, production)

# variables:
#   dockerRegistryServiceConnection: 'biswaDockerRegistryConnection'  # Replace with your actual service connection name

stages:
  - stage: Dockerize
    displayName: Build Docker Image
    dependsOn: Build   # Ensure the application is built before Dockerizing
    jobs:
      - job: BuildDockerImage
        displayName: Build Docker Image
        steps:
          - script: |
              echo "Checking Docker installation..."
              docker --version
            displayName: Verify Docker Installation

          - task: Docker@2
            displayName: Build Docker Image
            inputs:
              containerRegistry: $(dockerRegistryServiceConnection)
              repository: 'tweeter-authentication-service'
              command: 'build'
              Dockerfile: '$(Build.SourcesDirectory)/tweeter-authentication-service/Dockerfile'
              tags: |
                latest
                $(Build.BuildId)

  - stage: PushDockerImage
    displayName: Push Docker Image
    dependsOn: Dockerize
    jobs:
      - job: PushDocker
        displayName: Push Docker Image
        steps:
          - task: Docker@2
            displayName: Push Docker Image
            inputs:
              containerRegistry: $(dockerRegistryServiceConnection)
              repository: 'tweeter-authentication-service'
              command: 'push'
              tags: |
                latest
                $(Build.BuildId)
