version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: twitter_clone
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"  # Exposes MySQL port to the host
    volumes:
      - mysql_data:/var/lib/mysql  # Persist data in a volume
    networks:
      - twitter_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql  # Hostname of the MySQL service
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root  # Root password (same as MySQL)
    ports:
      - "8080:80"  # Exposes phpMyAdmin on port 8080 of the host
    depends_on:
      - mysql
    networks:
      - twitter_network

networks:
  twitter_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
