# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


# trigger:
# - master

# pool:
#   name: 'MyAgent'

# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'







trigger:
  branches:
    include:
      - master  # Trigger on changes to the master branch

pool:
  name: 'MyAgent'

stages:
  - stage: Build
    displayName: Build Auth Service
    jobs:
      - job: BuildAuthService
        displayName: Build Auth Service
        steps:
          # Step 1: Checkout code
          - checkout: self
            displayName: Checkout Code

          # Step 2: Set up JDK manually (if UseJavaVersion is unavailable)
          - script: |
              echo "Setting up Java 17..."
              export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
              export PATH=$JAVA_HOME/bin:$PATH
              java -version
            displayName: Set up Java 17

          # Step 3: Verify Maven setup
          - script: |
              echo "Checking Maven setup...------------------------------"
              mvn -version
              echo "PATH: $PATH"
            displayName: Verify Maven Setup

          # Step 4: Build the application with Maven
          - script: |
              echo "Building the application..."
              echo $pwd
              cd ..
              cd tweeter-authentication-service
              mvn clean package -DskipTests
            displayName: Build Spring Boot Application







# trigger:
#   branches:
#     include:
#       - master  # Trigger on changes to the main branch

# pool:
#   name: 'MyAgent'

# stages:
#   - stage: Build
#     displayName: Build Auth Service
#     jobs:
#       - job: BuildAuthService
#         displayName: Build Auth Service
#         steps:
#           # Step 1: Checkout code
#           - task: Checkout@1
#             displayName: Checkout Code

#           # Step 2: Set up JDK
#           - task: UseJavaVersion@1
#             inputs:
#               version: '17'  # Use Java 11 (adjust as per your project's requirements)
#               architecture: 'x64'

#           # Step 3: Build the Auth Service using Maven
#           - script: |
#               cd ..
#               cd tweeter-authentication-service
#               mvn clean install
#             displayName: Build with Maven

          # # Step 4: Build Docker image (Optional, if Docker is used)
          # - task: Docker@2
          #   displayName: Build Docker Image
          #   inputs:
          #     command: build
          #     Dockerfile: auth-service/Dockerfile
          #     tags: |
          #       auth-service:$(Build.BuildId)
